### ISSUE TITLE
OSHPark Compatible?

### ISSUE THREAD

**Issue by trevor403** [Gamer2020/GBA_Flash_Cart#2]
I only have two questions, will this design be OSHPark compatible, and is it in a working state as of yet? Oh also will there we a eeprom or some other type of flash save.

**Comment by Gamer2020** [comment]
All board deigns should be OSH compatible. Currently the only thing being tested is a cart dumper which has had mixed results. The first prototypes will have some kind of flash save. Currently this project is not being worked.
